services:
  - type: web
    name: stockflow-api
    runtime: docker
    dockerfilePath: backend/Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: CORS_ORIGINS
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
